package ReverseApp;

/**
* ReverseApp/ReverseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Sunday, 27 April, 2025 10:36:38 PM IST
*/

public final class ReverseHolder implements org.omg.CORBA.portable.Streamable
{
  public ReverseApp.Reverse value = null;

  public ReverseHolder ()
  {
  }

  public ReverseHolder (ReverseApp.Reverse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReverseApp.ReverseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReverseApp.ReverseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReverseApp.ReverseHelper.type ();
  }

}
