package ReverseApp;


/**
* ReverseApp/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Sunday, 27 April, 2025 10:36:38 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
  String uppercase (String str);
} // interface ReverseOperations
