package ReverseApp;


/**
* ReverseApp/Reverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Sunday, 27 April, 2025 10:36:38 PM IST
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
